### ISSUE TITLE
[Issue]: null stream event record will synchronize all stream when AMD_DIRECT_DISPATCH is set 

### ISSUE THREAD

**Issue by jiudianren** [ROCm-Developer-Tools/clr#105]
### Problem Description

![20455861500_159711089156_0FE651ED-2430-4280-8906-655D1501C130](https://github.com/user-attachments/assets/f61def92-e558-4e42-8ba9-2447b6de60e4)

event record at line 74 will sychronize all kernel at line 72  when AMD_DIRECT_DISPATCH is set . 
kernel is launched at other stream and  event is recorded at null stream.
What I saw was event recorded at line 74 will be executed  on host when all kernels  at line 72   are finished .
That is to say ， event recorded at line 74 is blocked at host.
but using with  cuda ,event recording is just for time  and it will not  synchronize with any stream.

### Operating System

ubuntu 22.04

### CPU

interel cpu

### GPU

M1300

### ROCm Version

ROCm 6.2.3

### ROCm Component

clr, HIP

**Comment by ppanchad-amd** [comment]
Hi @jiudianren. Internal ticket is created to investigate your issue. Thanks!

**Comment by schung-amd** [comment]
Hi @jiudianren, could you clarify what the issue is? I'm not sure what you're referring to with the line numbers, but cudaEventRecord does require synchronization: https://developer.download.nvidia.com/compute/DevZone/docs/html/C/doc/html/group__CUDART__EVENT_ga324d5ce3fbf46899b15e5e42ff9cfa5.html.

**Comment by jiudianren** [comment]
> Hi @jiudianren, could you clarify what the issue is? I'm not sure what you're referring to with the line numbers, but cudaEventRecord does require synchronization: https://developer.download.nvidia.com/compute/DevZone/docs/html/C/doc/html/group__CUDART__EVENT_ga324d5ce3fbf46899b15e5e42ff9cfa5.html.

sorry i upload an erro picture. and  I re-uploaded a photo with line numbers.  and added more detailed information. Please help me confirm if this is a problem，thanks a lot.

**Comment by jiudianren** [comment]
> Hi @jiudianren. Internal ticket is created to investigate your issue. Thanks!

Any feedback?

**Comment by schung-amd** [comment]
Sorry for the delay. This doesn't look like an issue to me; according to the CUDA docs, cudaEventRecord should also be doing this (i.e. waiting for all kernels in the context to finish; from the docs, "If stream is non-zero, the event is recorded after all preceding operations in stream have been completed; otherwise, it is recorded after all preceding operations in the CUDA context have been completed", also see https://stackoverflow.com/questions/5801717/cuda-cudaevent-t-and-cudathreadsynchronize-usage).

**Comment by jiudianren** [comment]
I have no doubt about your statement.but according to the CUDA docs(in your reply) , cudaEventRecord operation is asynchronous and it cannot blocking the execution on cpu.(from the docs, "Since operation is asynchronous, cudaEventQuery() and/or cudaEventSynchronize() must be used to determine when the event has actually been recorded.").
the example will be wait at cudaEventRecord(at line 74) untile all kernel be finished when ruing on AMD platform.
the example will be stop at cudaEventSynchronize(at line 78) untile all kernel be finished when ruing on NVIDIA platform.
This leads to a problem,if i want add some operations at line 76 which influence on kerenl's(at line 72) exit, they will be no chance of being executed.
I don't know if my question has been expressed clearly and thanks for your help.

**Comment by jiudianren** [comment]
> Sorry for the delay. This doesn't look like an issue to me; according to the CUDA docs, cudaEventRecord should also be doing this (i.e. waiting for all kernels in the context to finish; from the docs, "If stream is non-zero, the event is recorded after all preceding operations in stream have been completed; otherwise, it is recorded after all preceding operations in the CUDA context have been completed", also see https://stackoverflow.com/questions/5801717/cuda-cudaevent-t-and-cudathreadsynchronize-usage).

here is a another example 
![20455861500_160110622390_2BB21052-78DA-4b43-8C43-790B0608DC66](https://github.com/user-attachments/assets/4e22a52e-e67f-448f-a44c-00e814c6f89e)

**Comment by jiudianren** [comment]
> Sorry for the delay. This doesn't look like an issue to me; according to the CUDA docs, cudaEventRecord should also be doing this (i.e. waiting for all kernels in the context to finish; from the docs, "If stream is non-zero, the event is recorded after all preceding operations in stream have been completed; otherwise, it is recorded after all preceding operations in the CUDA context have been completed", also see https://stackoverflow.com/questions/5801717/cuda-cudaevent-t-and-cudathreadsynchronize-usage).

I have no doubt about your statement.
but when the  AMD_DIRECT_DISPATCH is set , there is a problem with the program.

According to the CUDA docs(in your reply) , cudaEventRecord operation is asynchronous and it cannot blocking the execution on cpu.(from the docs, "Since operation is asynchronous, cudaEventQuery() and/or cudaEventSynchronize() must be used to determine when the event has actually been recorded.").

the example will be stop at cudaEventRecord(at line 74) untile all kernel be finished when ruing on AMD platform.
the example will be stop at cudaEventSynchronize(at line 78) untile all kernel be finished when ruing on NVIDIA platform.
This leads to a problem,if I want add some operations at line 76 which influence on kerenl's(at line 72) exit, they will be no chance of being executed.
I don't know if my question has been expressed clearly and thanks for your help.

**Comment by jiudianren** [comment]
> Sorry for the delay. This doesn't look like an issue to me; according to the CUDA docs, cudaEventRecord should also be doing this (i.e. waiting for all kernels in the context to finish; from the docs, "If stream is non-zero, the event is recorded after all preceding operations in stream have been completed; otherwise, it is recorded after all preceding operations in the CUDA context have been completed", also see https://stackoverflow.com/questions/5801717/cuda-cudaevent-t-and-cudathreadsynchronize-usage).

here is another example when AMD_DIRECT_DISPATCH is set:

```
__global__ void test(uint32_t* flag)
{
	int i=0;
	while(*flag==0)
	{
		i++;
	}
}

int main()
{
	uint32_t* syncPtr= nullptr;
	cudaMallocHost(&syncPtr, sizeof(uint32_t));

	cudaEvent event;
	cudaStream_t stream;
	cudaStreamCreate(&stream);
	cudaEventCreate(&event);
	
	test<<<1,1,0,stream>>>(syncPtr);
	
	cudaEventRecord(event); /*host will stop at here on AMD platform when AMD_DIRECT_DISPATCH is set
	                        and the kernel cannot be finished so the program cannot be finished */

	*syncPtr=1;
	
	cudaEventSynchronize(event);/*on NVIDA platform, cudaEventRecord is asynchronous, and syncPtr will be set to 1,
	so the program will be finished after kernel be finished. 
	*/

	cudaEventDestory(event);
	cudaStreamDestory(stream);
}
```

**Comment by schung-amd** [comment]
Are you porting this to HIP or running this through CUDA? I can't reproduce this after porting your example to HIP:

```
#include <hip/hip_runtime.h>

__global__ void test(uint32_t* flag)
{
        int i=0;
        while(*flag==0)
        {
                i++;
        }
}

int main()
{
        uint32_t* syncPtr= nullptr;
        hipHostMalloc(&syncPtr, sizeof(uint32_t));

        hipEvent_t event;
        hipStream_t stream;
        hipStreamCreate(&stream);
        hipEventCreate(&event);

        test<<<1,1,0,stream>>>(syncPtr);

        hipEventRecord(event); /*host will stop at here on AMD platform when AMD_DIRECT_DISPATCH is set
                                and the kernel cannot be finished so the program cannot be finished */

        *syncPtr=1;

        hipEventSynchronize(event);/*on NVIDA platform, cudaEventRecord is asynchronous, and syncPtr will be set to 1,
        so the program will be finished after kernel be finished.
        */

        hipEventDestroy(event);
        hipStreamDestroy(stream);
}
```
completes fine with or without AMD_DIRECT_DISPATCH set. Tested on ROCm 6.2.3 + 7900XTX as well as ROCm 6.2.1 + MI200.

**Comment by jiudianren** [comment]
> Are you porting this to HIP or running this through CUDA? I can't reproduce this after porting your example to HIP:
> 
> ```
> #include <hip/hip_runtime.h>
> 
> __global__ void test(uint32_t* flag)
> {
>         int i=0;
>         while(*flag==0)
>         {
>                 i++;
>         }
> }
> 
> int main()
> {
>         uint32_t* syncPtr= nullptr;
>         hipHostMalloc(&syncPtr, sizeof(uint32_t));
> 
>         hipEvent_t event;
>         hipStream_t stream;
>         hipStreamCreate(&stream);
>         hipEventCreate(&event);
> 
>         test<<<1,1,0,stream>>>(syncPtr);
> 
>         hipEventRecord(event); /*host will stop at here on AMD platform when AMD_DIRECT_DISPATCH is set
>                                 and the kernel cannot be finished so the program cannot be finished */
> 
>         *syncPtr=1;
> 
>         hipEventSynchronize(event);/*on NVIDA platform, cudaEventRecord is asynchronous, and syncPtr will be set to 1,
>         so the program will be finished after kernel be finished.
>         */
> 
>         hipEventDestroy(event);
>         hipStreamDestroy(stream);
> }
> ```
> 
> completes fine with or without AMD_DIRECT_DISPATCH set. Tested on ROCm 6.2.3 + 7900XTX as well as ROCm 6.2.1 + MI200.

I haven't verified this example, I assume all are the same behavior. i am so sorry for that.
and I have verified the example on  rocm  4.2.0  + Radeon RX Vega 64. it is rellay passed. 
but when i check the hip log,  the log of kernel command finished is before the success log of hipEventRecord, i have no idea about this behavior.


here is another example, I have verified this case on  rocm  4.2.0  + Radeon RX Vega 64 + AMD_DIRECT_DISPATCH=1. it will block at host.
device function sleepMs instead of i++ in while.

```
#include <hip/hip_runtime.h>
#define CLOCK_RATE 1695000
__device__ void sleepMs(float t)
{
	clock_t t0=clock64();
	clock_t t1=t0;
	while((t1-t0)/(CLOCK_RATE*1000.0f) < t)
	{
		t1=clock64();
	}
}

__global__ void test(uint32_t* flag)
{
        int i=0;
        while(*flag!=1)
        {
			//printf("do while:%d\n",i++);
			sleepMs(1.0);
        }
}

int main()
{
	uint32_t* syncPtr= nullptr;
	hipHostMalloc(&syncPtr, sizeof(uint32_t));

	hipEvent_t event;
	hipStream_t stream;
	hipStreamCreate(&stream);
	hipEventCreate(&event);

	test<<<1,1,0,stream>>>(syncPtr);
	
	hipEventRecord(event); 
	*syncPtr=1;
	hipEventSynchronize(event);
	hipEventDestroy(event);
	hipStreamDestroy(stream);
}
```

**Comment by schung-amd** [comment]
Thanks for the reproducer, there's some interesting behavior here. This does lock up for me with or without `AMD_DIRECT_DISPATCH` set, but also doesn't even need to sleep; simply calling `clock64()` will cause the lock:
```
__global__ void test(uint32_t* flag)
{
    while(*flag!=1)
    {
        clock64();
    }
}
```
However, upon inserting a `printf` into this loop, the program functions as expected (i.e. some amount of loop iterations are performed until the flag is set, at which point the kernel completes).

It seems like in the loop with only timing functions, the compiler is optimizing away the kernel's access to the current flag value. You should use the `volatile` keyword for your flag to ensure this doesn't happen. When I define the kernel as
```
__global__ void test(volatile uint32_t* flag)
{
    while(*flag!=1)
    {
        clock64();
    }
}
```
it completes as expected.

A couple of asides:

- Your reproducer code with the `sleepMs` device function works properly with `volatile` on MI200 but not on the 7900XTX; this is because the timing functions `clock()` and `clock64()` do not currently function correctly on RDNA3 (see https://rocm.docs.amd.com/projects/HIP/en/latest/reference/cpp_language_extensions.html#timer-functions), so the sleep is not measured properly.
- ROCm 4.2 is fairly old and we don't currently support gfx900 cards, so any difference in behavior between your system and what I'm seeing may be due to this.

**Comment by jiudianren** [comment]
The initial suspicion was WaitActiveStreams called from hipEventRecord will block host executiong.  Now it seems that this idea is wrong. 
Thanks for your help.
