### ISSUE TITLE
missing atomicMin/Max for signed long long in HIP (available in CUDA)

### ISSUE THREAD

**Issue by Epliz** [ROCm-Developer-Tools/clr#2]
Hi,

As pointed out at https://github.com/ROCm-Developer-Tools/hipamd/issues/65 , there is not version of the atomicMin/Max methods for signed long long arguments.
These variants are available in CUDA as seen at https://docs.nvidia.com/cuda/cuda-c-programming-guide/#atomicmin (as well as in OpenCL on AMD GPUs).
Therefore it seems like they should be added.

Best regards,
Epliz

**Comment by jatinx** [comment]
Thanks for reporting it. Will look at it.

**Comment by cjatin** [comment]
Fixed via: https://github.com/ROCm-Developer-Tools/clr/commit/be02e1e524b0592cd34d25994e8d3b3d6094bed0
