### ISSUE TITLE
Do you have a plan to upgrade opencl header version to 3.0 ?

### ISSUE THREAD

**Issue by loonyma** [ROCm-Developer-Tools/clr#20]

**Comment by sh-zheng** [comment]
It seems that Nvidia and Intel Arc all support opencl 3.0 now.

**Comment by tcgu-amd** [comment]
@loonyma We are currently looking into upgrading to ~~opencl 3.0~~ header version 3.0. Please keep an eye out for announcements/updates in the future for more details. Thanks!

**Comment by tcgu-amd** [comment]
To clarify: we are testing out supporting header version 3.0 and are hitting some bumps, but it is currently not on our roadmap yet. And we have no plans to support OpenCL 3.0 in the runtime as of now. Apologies if my previous response caused any confusion. Thanks!
