### ISSUE TITLE
How to insert cxx flag '-fno-stack-protector' for clang when using rtc?

### ISSUE THREAD

**Issue by littlewu2508** [ROCm-Developer-Tools/clr#21]
On Gentoo distribution where `/etc/clang/gentoo-hardened.cfg` put `-fstack-protector-strong` by default, but that cause errors in compiling AMDGPU kernels. We have manually add `-fno-stack-protector` to `hipcc` to avoid issues like https://bugs.gentoo.org/890377, but I have encountered similar one when running rocFFT-5.7.1 tests:

```
[ RUN      ] pow2_1D/accuracy_test.vs_fftw/real_forward_len_2_double_ip_batch_4_istride_1_R_ostride_1_HI_idist_4_odist_2_ioffset_0_0_ooffset_0_0
LLVM ERROR: Cannot select: 0x7f0a5820b760: i64 = FrameIndex<0>
In function: fft_rtc_fwd_len1_factors_1_wgs_64_tpt_1_dim1_dp_ip_CI_unitstride_sbrr_R2C_dirReg_CB
LLVM ERROR: Cannot select: 0x560eae9a0a00: i64 = FrameIndex<0>
In function: fft_rtc_fwd_len1_factors_1_wgs_64_tpt_1_dim1_dp_ip_CI_unitstride_sbrr_R2C_dirReg
```

If I comment out `-fstack-protector-strong` in `/etc/clang/gentoo-hardened.cfg` the test can execute normally.

it seems that it uses `rtc`, which reads `/etc/clang/gentoo-hardened.cfg`. So, as a workaround, how can I put `-fno-stack-protector` as a compilation arg to rtc?

**Comment by cjatin** [comment]
rtc adds a fixed number of options to clang call which can be found here: https://github.com/ROCm-Developer-Tools/clr/blob/76e3ffeb8178c6e32e2ee9a61b9fb0ec7ca39414/hipamd/src/hiprtc/hiprtcInternal.cpp#L154

I think clang might be picking up these options from that file and appending it to them.

Can you paste the dump of clang call, via env variable `AMD_COMGR_EMIT_VERBOSE_LOGS=1` and running the test.

cc'ing: @yxsamliu

**Comment by yxsamliu** [comment]
a recent clang change has disabled stack protector for amdgpu

https://github.com/llvm/llvm-project/pull/70799

so no need to pass the option with the fix

**Comment by littlewu2508** [comment]
> a recent clang change has disabled stack protector for amdgpu
> 
> [llvm/llvm-project#70799](https://github.com/llvm/llvm-project/pull/70799)
> 
> so no need to pass the option with the fix

Thank you, that is much better than setting the flag which also disables stack protector on CPU code generation. I'll try the fix.

**Comment by AngryLoki** [comment]
For other similar flags: the answer was:
```
-Xarch_host -fstack-clash-protection
-Xarch_host -fstack-protector-strong
-Xarch_host -fcf-protection=full
```
There is also `--no-default-config` flag which completely disables all flags from config, but I think it is harmful, as better option (`-Xarch_host` and `-Xarch_device`) exist.

Another related task in llvm-project: https://github.com/llvm/llvm-project/issues/86450

**Comment by ppanchad-amd** [comment]
Hi @littlewu2508, do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by littlewu2508** [comment]
> do you still need assistance with this ticket

The `-fno-stack-protector` issue is fixed and `-fcf-protection` is tracked in https://github.com/llvm/llvm-project/issues/86450

However, concerning the issue itself, I'm still curious about how to inject custom flags when using rtc, which gives us more flexibility

**Comment by ppanchad-amd** [comment]
@littlewu2508 Created an internal ticket to assist with your question. Thanks!

**Comment by tcgu-amd** [comment]
Hi @littlewu2508, not sure this answers your question, but in general, you can pass clang flags to the hiprtcCompileProgram function when using hiprtc, as per official documentation [here](https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/user_guide/hip_rtc.html#example). The corresponding source code is defined in https://github.com/ROCm/clr/blob/cfdc9dfc36218582a554b10e94d88a8e7b00f791/hipamd/src/hiprtc/hiprtc.cpp#L113. Please let me know if you have further questions. Thanks!

**Comment by tcgu-amd** [comment]
Hi, this issue will be closed now due to inactivity. Please feel free to reopen/ask follow up questions should further assistance be required. Thanks!
