### ISSUE TITLE
hipUserObjectRetain return hipErrorInvalidValue?

### ISSUE THREAD

**Issue by Dustray** [ROCm-Developer-Tools/clr#25]
Should it be returning unsuccessful?

```
hipError_t hipUserObjectRetain(hipUserObject_t object, unsigned int count) {
  HIP_INIT_API(hipUserObjectRetain, object, count);
  if (object == nullptr || count == 0 || count > INT_MAX) {
    HIP_RETURN(hipErrorInvalidValue);
  }
  if (!hipUserObject::isUserObjvalid(object)) {
    HIP_RETURN(hipSuccess);  <<<<<<<<<<<<<
  }
  object->increaseRefCount(count);
  HIP_RETURN(hipSuccess);
}
```

https://github.com/ROCm-Developer-Tools/clr/blob/9fdee05aeea7db0e20bc65770556aefd1d2c78f0/hipamd/src/hip_graph.cpp#L2460C20-L2460C20

**Comment by iassiour** [comment]
Returning success when the userObject is invalid seems to be consistent with cuda behaviour. But it is counter-intuitive. Let me follow up on this.

**Comment by huanrwan-amd** [comment]
@Dustray This part matches CUDA's behavior. Therefore, we close the ticket as invalid.
