### ISSUE TITLE
Out-of-date install instructions within hipamd

### ISSUE THREAD

**Issue by whydoubt** [ROCm-Developer-Tools/clr#27]
`hipamd/INSTALL.md` contains build instructions that are rendered out-of-date with ROCM 5.6 and the moving of `hipamd` and `ROCclr` into the current `clr` repo.  Those instructions should be either updated, removed, or at least have a warning banner added.

**Comment by iassiour** [comment]
Thanks @whydoubt, I think this file can be removed. I will raise a PR internally to fix this.

**Comment by iassiour** [comment]
The change has been merged in clr develop branch https://github.com/ROCm-Developer-Tools/clr/commit/f6e0f2613cf0190d41656418a05c6916c2fabe7c.
Closing this issue.
