### ISSUE TITLE
HIPCC_VERBOSE breaks cmake variables

### ISSUE THREAD

**Issue by gotzl** [ROCm-Developer-Tools/clr#28]
`hip-config-amd.cmake` uses [`HIPCC` to fill some variable](https://github.com/ROCm-Developer-Tools/clr/blob/c3bd229f4fcae24c8cc41f34696557ee3b59e8ad/hipamd/hip-config-amd.cmake#L164C24-L164C24). If `HIPCC_VERBOSE` is enabled, this variable includes debug strings, which later on breaks the build.

It was not super obvious for me to find this when my build failed, so I just want to avoid others from shooting them in the foot .. I suggest to maybe call `HIPCC` explicitly with `HIPCC_VERBOSE=0`?

**Comment by cjatin** [comment]
Thanks for letting us know.
Will raise a PR internally to fix this.

**Comment by cjatin** [comment]
https://github.com/ROCm-Developer-Tools/clr/commit/515d07cb3ab7b2f206cfded0c7f288e01a0282f1
