### ISSUE TITLE
Support non-x86_64 platform

### ISSUE THREAD

**Issue by Xeonacid** [ROCm-Developer-Tools/clr#32]
Hi,
Some code uses `<immintrin.h>` which cannot be built on non_x86_64 platform. Could you add a fallback generic implementation?
Thanks!

**Comment by cjatin** [comment]
can you share a bit more information.

Which platform are you using?
The file from which the error is originating?
you gpu config?

**Comment by Xeonacid** [comment]
> Which platform are you using?

RISC-V. In my case.

> The file from which the error is originating?

https://github.com/ROCm-Developer-Tools/clr/blob/develop/rocclr/device/rocm/rocvirtual.cpp as you can see in #35

**Comment by cjatin** [comment]
raised a PR internally for this.

**Comment by cjatin** [comment]
PR: https://github.com/ROCm/clr/commit/12461dbd6a26e02d03b572399b6d629f44b0a318

**Comment by darkbasic** [comment]
At least on ppc64le I do have such header:
```
./usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/immintrin.h
./usr/lib/clang/15.0.7/include/ppc_wrappers/immintrin.h
./usr/lib/clang/15.0.7/include/immintrin.h
./usr/lib/clang/17/include/ppc_wrappers/immintrin.h
./usr/lib/clang/17/include/immintrin.h
```

Unfortunately even if it compiles fine I get runtime errors: https://github.com/ROCm/clr/issues/61

@Xeonacid does it work for you on RISC-V?

**Comment by ppanchad-amd** [comment]
@Xeonacid Closing ticket.  Please re-open if you still need further assistance with this ticket. Thanks!
