### ISSUE TITLE
Odd behaviour with darktable watermarks on Framework 13 AMD 7840U

### ISSUE THREAD

**Issue by etrigan63** [ROCm-Developer-Tools/clr#33]
I have a Framework 13 AMD (Ryzen 7840U, 64GB RAM, 2TB nvme) with the `rocm-opencl-runtime` installed. `darktable` recognizes the GPU but when I export an image that has a `simple-text-shadow` watermark, the following happens:
![dog1](https://github.com/ROCm-Developer-Tools/clr/assets/7347264/6e0b51c6-f491-4f38-80b3-4cb14d834c96)
If I switch to `simple-text` it works correctly:
![dog2](https://github.com/ROCm-Developer-Tools/clr/assets/7347264/9c06663b-d5f1-486f-9a02-39dded1b8842)
I contacted the `darktable` folks and they threw you guys under the bus.

**Comment by etrigan63** [comment]
These same drivers behave normally on my AMD desktop (Ryzen 9 5950X + 6750XT).

**Comment by cjatin** [comment]
can you share the output of `rocminfo`, `rocm_agent_enumerator` and `clinfo`

Can you also link to the darktable issue which might have more information

**Comment by ppanchad-amd** [comment]
@etrigan63 Closing ticket for now. Please re-open if you still see the issue with the latest ROCm. Thanks!
