### ISSUE TITLE
The calls to currentStackInfo cause issues if a library uses stackful coroutines

### ISSUE THREAD

**Issue by gbaraldi** [ROCm-Developer-Tools/clr#36]
So the context here is https://github.com/JuliaGPU/AMDGPU.jl/issues/549 where julia switches the thread stack in to have goroutine like tasks. But that causes some issues, specifically in the call to https://github.com/ROCm-Developer-Tools/clr/blob/1a0c3e4dc45237716c08a6b74be5ff6405422ead/rocclr/os/os_posix.cpp#L290-L312 from https://github.com/ROCm-Developer-Tools/clr/blob/d96481fb3609720058180ca5aa02b1da57df68a5/rocclr/thread/thread.cpp#L32-L36  . 
Taking a quick look, it doesn't seem that the `stackBase_` and `stackSize_` fields are used anywhere in the library, so I was curious if they have any use, or if they could be removed in order to avoid issues like these

**Comment by pxl-th** [comment]
Can someone confirm if these can be safely removed?

**Comment by ppanchad-amd** [comment]
@gbaraldi Apologies for the lack of response. Internal ticket has been created to look into this issue. Thanks!

**Comment by zichguan-amd** [comment]
Hi @gbaraldi @pxl-th, thanks for reaching out. I could not reproduce the issue on ROCm 6.2.0 and Julia 1.10.5. Can you confirm if the issue has been resolved?

**Comment by zichguan-amd** [comment]
Closing the issue due to inactivity.
