### ISSUE TITLE
Why don't we just set all the fences to dirty?

### ISSUE THREAD

**Issue by Dustray** [ROCm-Developer-Tools/clr#38]
I noticed a lock before resetFenceDirty() in iHipWaitActiveStreams(https://github.com/ROCm/clr/commit/3c6505c2d5988050f8282f556ff654ab3b2e31a1). The question I have is why don't we just set all the fences to dirty after dispatchBarrierPacket(https://github.com/ROCm/clr/blob/b825decd422500b58e983f1a2f79c9c5f9df3cbd/rocclr/device/rocm/rocvirtual.cpp#L1053).

Would adding another lock and loop for this hurt performance?

Why can't other CacheState just set dirty like `kCacheStateSystem`?

Thanks and hope you answer!

**Comment by ppanchad-amd** [comment]
Hi @Dustray. Apologies for the lack of response. Internal ticket has been created to assist with your question. Thanks!

**Comment by schung-amd** [comment]
Hi @Dustray, is this question still relevant? I'll reach out to our internal teams if it is, but our codebase has changed in the meanwhile and I don't see `iHipWaitActiveStreams` anymore. Let me know if this has just been refactored and your question is still relevant, or if you have any questions about the current code.

**Comment by Dustray** [comment]
Ok I found that the locking judgment against isFenceDirty() has been removed in iHipWaitActiveStreams（now is Device::WaitActiveStreams()）.

**Comment by schung-amd** [comment]
Thanks for following up!
