### ISSUE TITLE
Enable DEBUG_CLR_GRAPH_PACKET_CAPTURE, the packet capture function can't work with kernel node modified by hipGraphExecKernelNodeSetParams

### ISSUE THREAD

**Issue by kevin-gjm** [ROCm-Developer-Tools/clr#42]
precondition: enable DEBUG_CLR_GRAPH_PACKET_CAPTURE

steps: 
1. hipGraphCreate
2. hipGraphAddKernelNode
3. hipGraphInstantiate
4. hipGraphExecKernelNodeSetParams
5. hipGraphLaunch
6. hipStreamSynchronize

 After function hipGraphInstantiate, the AQL packet is generated by CaptureAQLPackets which will be used in hipGraphLaunch step. 

But when with hipGraphExecKernelNodeSetParams, the AQL will be modified, and the modified AQL will not executed in hipGraphLaunch.

 I think this is an issue.

**Comment by iassiour** [comment]
Thank you @kevin-gjm for raising. I can see the issue from the steps above as the kernel argument offset in particular may become outdated after hipGraphExecKernelNodeSetParams. Would it be possible to share a small reproducer program if you have one already?

**Comment by iassiour** [comment]
This has been fixed in an internal PR.

**Comment by iassiour** [comment]
The fix has been added to develop branch https://github.com/ROCm/clr/commit/a99b163eba57947e77e583494537717a52bc3803 and will be included in a future rocm release.
