### ISSUE TITLE
 [QA] error: use of undeclared identifier '__asm__'

### ISSUE THREAD

**Issue by qiji2023** [ROCm-Developer-Tools/clr#59]
### Problem Description

I use inline asm in opencl code, but I get a error ` error: use of undeclared identifier '__asm__'` on RX588 with driver 20.4.2

it is ok on RX6900xt, but the error will appear on RX 588

my code is like:
```
 __asm__ volatile("v_mad_u64_u32 %[t], null, %[aj], %[bi], 0;"      \
                           : [t] "=v"(tl[j])                                 \
                           : [aj] "v"(a->data[j]), [bi] "v"(b->data[i]));    \
```

### Operating System

window10

### CPU

amd R9

### GPU

AMD Radeon VII

### ROCm Version

ROCm 5.5.0

**Comment by qiji2023** [comment]
@amd-aakash can you help me?

**Comment by ppanchad-amd** [comment]
Hi @qiji2023, apologies for the lack of response.  I have created an internal ticket to assist with your issue. Thanks!

**Comment by darren-amd** [comment]
Hi @qiji2023,

I tried running some basic assembly code and was unable to reproduce the issue. I suspect that the error message could be related to the compiler not recognizing the `___asm___` declaration. 

Could you please let me know which compiler you are using (along with the version), as well as how you are compiling the code (any flags you are passing)? Thanks!

**Comment by darren-amd** [comment]
Hi @qiji2023,

I'm going to close this ticket due to inactivity, please feel free to create another one if the issue persists, thanks!
