### ISSUE TITLE
Update AMD_PLATFORM_BUILD_NUMBER

### ISSUE THREAD

**Issue by preda** [ROCm-Developer-Tools/clr#68]
In rocclr/utils/versions.hpp there is:
```
#define AMD_PLATFORM_BUILD_NUMBER 3581
```
https://github.com/ROCm/clr/blob/ad32e604c7f286a28d90e92d3936401c964d6de2/rocclr/utils/versions.hpp#L31

Which was last updated in March *2023* (one year ago).

But the same value for ROCm 6.1RC is 3614 ATM.

Please keep this public repo in sync with the ROCm that is released and with the ROCm RC.

This version number is useful to track which changes are where. I don't understand how the version here in the public repo was not updated for a year? while there are ongoing commits to this public repo. Is this a problem with the version number being out-of-sync, or is the situation that changes to CLR since one year ago didn't make it here in the open yet?

**Comment by mangupta** [comment]
@preda : We update the version when we merge changes from our development branch (amd-staging) to mainline branch (amd-mainline). The commit you are looking at is in the development branch in which we do not bump this version. Please refer to https://github.com/ROCm/clr/blob/amd-mainline/rocclr/utils/versions.hpp#L31 where you can see that the version is being regularly updated.
