### ISSUE TITLE
[Issue]: no definition of struct tiled_partition_internal 

### ISSUE THREAD

**Issue by onepick** [ROCm-Developer-Tools/clr#88]
### Problem Description

in the file :include/hip/amd_detail/amd_hip_cooperative_groups.h
`

> namespace impl {
> template <unsigned int size, class ParentCGTy> **struct tiled_partition_internal**;
> 
> template <unsigned int size>
> struct tiled_partition_internal<size, thread_block> : public thread_block_tile<size, thread_block> {
>   __CG_QUALIFIER__ tiled_partition_internal(const thread_block& g)
>       : thread_block_tile<size, thread_block>(g) {}
> };
> 
> }  // namespace impl

`

there is no definition for the struct **tiled_partition_internal**.

### Operating System

any os

### CPU

any cpu

### GPU

AMD Instinct MI250

### ROCm Version

ROCm 6.1.0

### ROCm Component

clr

**Comment by cjatin** [comment]
There is a specialization of tiled_partition_internal but just for thread_block.

Is there a sample thats failing for you?

**Comment by ppanchad-amd** [comment]
Hi @onepick, do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@onepick Closing ticket. Please feel free to re-open ticket if you still need assistance. Thanks!
