### ISSUE TITLE
[Issue]: question about source code: https://github.com/ROCm/clr/blob/amd-staging/rocclr/platform/memory.cpp#L526

### ISSUE THREAD

**Issue by donaldkuck** [ROCm-Developer-Tools/clr#92]
### Problem Description

In https://github.com/ROCm/clr/blob/amd-staging/rocclr/platform/memory.cpp#L526 
 amd::Os::commitMemory return value is not checked, does mmap always success in this situation ? 

### Operating System

ubuntu 24.04

### CPU

3700x

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.0

### ROCm Component

clr

### Steps to Reproduce

none

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

none

### Additional Information

none

**Comment by ppanchad-amd** [comment]
Hi @SpinEch0, internal ticket has been created to answer your question. Thanks!

**Comment by zichguan-amd** [comment]
Hi @SpinEch0, thanks for pointing it out. Although we haven't seen any issues related to `mmap` failing, we will work on a patch to check the error code.

**Comment by zichguan-amd** [comment]
Hi @SpinEch0, the changes have been merged into staging, see 74ebbe17e915e3ae49a1b900e802769a048da442.
