### ISSUE TITLE
[Feature]: Eager Loading of HIP Modules Should Trigger Initialization of Static Managed Variables

### ISSUE THREAD

**Issue by matinraayai** [ROCm-Developer-Tools/clr#96]
### Suggestion Description

When setting the environment variable `HIP_ENABLE_DEFERRED_LOADING` to zero, the HIP runtime triggers the loading of the static HIP modules on all devices right after they are registered; However, eager loading does not initialize the static managed variables of the modules; More specifically, even though it allocates an SVM memory for that variable and initializes it, it does not write the address of the SVM chunk of memory to the ELF variable reserved for it inside the HIP module for each device. This in my opinion does not comply with the behavior of eager loading.

One possible fix for this is to make `__hipRegisterManagedVar` mimic what `__hipRegisterFunction` does, which ends up like the following code:
```c++
void __hipRegisterManagedVar(
    void *hipModule,  // Pointer to hip module returned from __hipRegisterFatbinary
    void **pointer,   // Pointer to a chunk of managed memory with size \p size and alignment \p
    // align HIP runtime allocates such managed memory and assign it to \p pointer
    void *init_value,  // Initial value to be copied into \p pointer
    const char *name,  // Name of the variable in code object
    size_t size, unsigned align) {
    HIP_INIT_VOID();
    hipError_t status = ihipMallocManaged(pointer, size, align);
    if (status == hipSuccess) {
        hip::Stream *stream = hip::getNullStream();
        if (stream != nullptr) {
            status = ihipMemcpy(*pointer, init_value, size, hipMemcpyHostToDevice, *stream);
            guarantee((status == hipSuccess), "Error during memcpy to managed memory, error:%d!",
                      status);
        } else {
            ClPrint(amd::LOG_ERROR, amd::LOG_API, "Host Queue is NULL");
        }
    } else {
        guarantee(false, "Error during allocation of managed memory!, error: %d", status);
    }
    hip::Var *var_ptr = new hip::Var(std::string(name), hip::Var::DeviceVarKind::DVK_Managed, pointer,
                                     size, align, reinterpret_cast<hip::FatBinaryInfo **>(hipModule));
    status = PlatformState::instance().registerStatManagedVar(var_ptr);
    guarantee((status == hipSuccess), "Cannot register Static Managed Var, error: %d", status);
    static int enable_deferred_loading{[]() {
      char *var = getenv("HIP_ENABLE_DEFERRED_LOADING");
      return var ? atoi(var) : 1;
    }()};

    if (!enable_deferred_loading) {
        HIP_INIT_VOID();
        for (int dev_idx = 0; dev_idx < g_devices.size(); ++dev_idx) {
            status = PlatformState::instance().initStatManagedVarDevicePtr(dev_idx);
            guarantee((status == hipSuccess), "Cannot initialize static managed variable, error: %d",
                      status);
        }
    }
}
```
Though I have tested this modification on my end, I think better solutions probably exist. 

### ROCm Component

CLR

**Comment by tcgu-amd** [comment]
Hi @matinraayai, thanks for reaching out! At this moment, HIP_ENABLE_DEFERRED_LOADING is not an officially supported variable and is mainly used for internal debugging purposes only. Unfortunately, we do not currently have any plans on officially supporting it anytime soon. Please refer to https://rocm.docs.amd.com/projects/HIP/en/latest/reference/env_variables.html for a list of fully supported environment variables. Thanks!

**Comment by matinraayai** [comment]
@tcgu-amd thanks you for the response. My use case is experimental and I don't require official support for this, at least not yet. Even if the environment variable is not officially supported and is intended for debugging, this bug should be worth fixing, as right now the eager loading feature doesn't work as intended. This should be a small fix, and should have any adverse side-effects on the runtime.

**Comment by tcgu-amd** [comment]
@matinraayai Yes we certainly agree -- what you propose does makes sense, and again thanks for pointing it out, we really do appreciate it! A lot of these internal ENV variables are used to debugging specific cases only, and this variable in particular was not really intended to fully deliver the functionality of eager loading. We will see if we can get it fixed, but since it is not supported we can't really make any promises at the moment. What likely will happen is that if we encounter future bug involving eager loading of managed variables then this one will probably be updated as part of the debugging process.

**Comment by matinraayai** [comment]
@tcgu-amd thanks. Please let me know if any updates happen on your side.
